### ISSUE TITLE
Solved: Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by jrubialesv** [jrubialesv/my_spark_scala_java_errros#1]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.unsafe.array.ByteArrayMethods.<clinit>(ByteArrayMethods.java:54)
	at org.apache.spark.internal.config.package$.<init>(package.scala:1006)
	at org.apache.spark.internal.config.package$.<clinit>(package.scala)
	at org.apache.spark.SparkConf$.<init>(SparkConf.scala:639)
	at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala)
	at org.apache.spark.SparkConf.set(SparkConf.scala:94)
	at org.apache.spark.SparkConf.set(SparkConf.scala:83)
	at org.apache.spark.SparkConf.setMaster(SparkConf.scala:115)
	at org.apache.spark.SparkContext$.updatedConf(SparkContext.scala:2698)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:148)
	at com.sundogsoftware.spark.HelloWorld$.main(HelloWorld.scala:11)
	at com.sundogsoftware.spark.HelloWorld.main(HelloWorld.scala)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @130d63be
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:192)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:185)
	at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:56)
	... 12 more

**Comment by jrubialesv** [comment]
Running scala file in a project results the error above

what fix it was changing java19 to java8: https://www.oracle.com/java/technologies/downloads/#java8

You need to change the path of the environment variable to the correct path
